### ISSUE TITLE
Bug: server error when trying to set some field as relation field

### ISSUE THREAD

**Issue by Ilya-Green** [jowilf/starlette-admin#124]
Set 
`field = [
    "id",
    RelationField("some_relation")
]`
=> 

404 Not found when trying to acces site.
Same with "HasOne", "HasMany".

I know that it works automaticly, but when i want to modify this field and set to specific ModelView, it will not work through.
When I tried to make just plain new field (and set it to relation field) to display some information instead "id" it also lead to error (but after opening first both connected modelview; first time some one of them works perfect and displays correct information).

```
@dataclass
class NotesField(StringField):
    """This field is used to represent any kind of long text content.
    For short text contents, use [StringField][starlette_admin.fields.StringField]"""

    rows: int = 6
    class_: str = "field-textarea form-control"
    form_template: str = "forms/textarea.html"
    display_template: str = "displays/notes.html"

    def input_params(self) -> str:
        return html_params(
            {
                "rows": self.rows,
                "minlength": self.minlength,
                "maxlength": self.maxlength,
                "placeholder": self.placeholder,
                "required": self.required,
                "disabled": self.disabled,
                "readonly": self.read_only,
            }

        )

    async def serialize_value(
        self, request: Request, value: Any, action: RequestAction
    ) -> str:
        return value
        
class TestView(MyModelView):
    fields = [
        Test.id,
        NotesField("notes"),
        ]
```

=>
```
TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Note is not JSON serializable
```

**Environment (please complete the following information):**
 - Starlette-Admin version: 0.6.0
 - ORM/ODMs: sqlmodel==0.0.8(SQLAlchemy==1.4.41, sqlalchemy2-stubs==0.0.2a32)

**Comment by jowilf** [comment]
It's not clear for me what you are trying to achieve, but look at my comment

```py
@dataclass
class NotesField(StringField):
    """This field is used to represent any kind of long text content.
    For short text contents, use [StringField][starlette_admin.fields.StringField]"""

    rows: int = 6
    class_: str = "field-textarea form-control"
    form_template: str = "forms/textarea.html"
    display_template: str = "displays/notes.html"

    def input_params(self) -> str:
        return html_params(
            {
                "rows": self.rows,
                "minlength": self.minlength,
                "maxlength": self.maxlength,
                "placeholder": self.placeholder,
                "required": self.required,
                "disabled": self.disabled,
                "readonly": self.read_only,
            }

        )

    async def serialize_value(
        self, request: Request, value: Any, action: RequestAction
    ) -> str:
        # make sure the returned value is JSON Serializable. You are using string templates, so it should return string
        # you can return different value based on `action`.
        return value 
        
class TestView(MyModelView):
    fields = [
        Test.id,
        NotesField("notes"),
        ]
```

**Comment by Ilya-Green** [comment]
The main idea to display some information in relation field. Currently, RelationField dispays only id.

There are models Post and Note that have relation with foreign_key in post_id

```
class Post(SQLModel, table=True):
    id: Optional[int] = Field(primary_key=True)

    notes: List["Note"] = Relationship(back_populates="post")

class Note(SQLModel, table=True):
    id: Optional[int] = Field(primary_key=True)
    content: str = Field(sa_column=Column(Text), min_length=5)

    post_id: Optional[int] = Field(foreign_key="post.id")
    post: Client = Relationship(back_populates="notes")
```

When I'm trying to redefine relation field in ModelView as RelationalField it returns:
```
class PostView(MyModelView):
    fields = [
        Post.id,
        RelationField("notes"),
```
`INFO:     127.0.0.1:3054 - "GET /api/client?skip=0&limit=20&order_by=id%20asc HTTP/1.1" 404 Not Found`
Same happens when I try to set as "HasMany" or "HasOne":
```
class PostView(MyModelView):
    fields = [
        Post.id,
        HasMany("notes"),
```
`INFO:     127.0.0.1:3054 - "GET /api/client?skip=0&limit=20&order_by=id%20asc HTTP/1.1" 404 Not Found`
```
class PostView(MyModelView):
    fields = [
        Post.id,
        HasOne("notes"),
```
`INFO:     127.0.0.1:3054 - "GET /api/client?skip=0&limit=20&order_by=id%20asc HTTP/1.1" 404 Not Found`

So since i dont know how to set field as RelationField a can't modify RelationField to display some additional information because i cant set fields as new field type.

I've tried to create new field based on TextField:

```
@dataclass
class NotesField(StringField):
    """This field is used to represent any kind of long text content.
    For short text contents, use [StringField][starlette_admin.fields.StringField]"""

    rows: int = 6
    class_: str = "field-textarea form-control"
    form_template: str = "forms/textarea.html"
    display_template: str = "displays/notes.html"

    def input_params(self) -> str:
        return html_params(
            {
                "rows": self.rows,
                "minlength": self.minlength,
                "maxlength": self.maxlength,
                "placeholder": self.placeholder,
                "required": self.required,
                "disabled": self.disabled,
                "readonly": self.read_only,
            }

        )
        
class ClientsView(MyModelView):
    fields = [
        Client.id,
        NotesField("notes"),
```
It works and returns text on view:
`
[Note(content='rrrrrrrr', id=1, created_at=datetime.datetime(2023, 3, 15, 17, 21, 45, 410730), post_id=1))] 
`
But if i want to display only some of the attributes, i need to define `def serialize_value` to work with value in html:
```
    def input_params(self) -> str:
        return html_params(
            {
                "rows": self.rows,
                "minlength": self.minlength,
                "maxlength": self.maxlength,
                "placeholder": self.placeholder,
                "required": self.required,
                "disabled": self.disabled,
                "readonly": self.read_only,
            }

        )

    async def serialize_value(
        self, request: Request, value: Any, action: RequestAction
    ) -> str:
        return value
```
notes.html:
```
{%if data | is_iter %}
<ul>
  {% for value in data %}
  <li>
  {{ value.content }}
  </li>
  {% endfor %}
</ul>
{%else%}

{%endif%}
```
It displays information on detail. But when I'm trying to go to list ("admin/post/list") it displays base interface, but dont displays list of posts and return error in uvicorn:
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "E:\cygwin64\git\crm_broker\venv\lib\site-packages\anyio\streams\memory.py", line 94, in receive
    return self.receive_nowait()
  File "E:\cygwin64\git\crm_broker\venv\lib\site-packages\anyio\streams\memory.py", line 89, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\cygwin64\git\crm_broker\venv\lib\site-packages\starlette\middleware\base.py", line 78, in call_next
    message = await recv_stream.receive()
  File "E:\cygwin64\git\crm_broker\venv\lib\site-packages\anyio\streams\memory.py", line 114, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\cygwin64\git\crm_broker\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "E:\cygwin64\git\crm_broker\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "E:\cygwin64\git\crm_broker\venv\lib\site-packages\fastapi\applications.py", line 271, in __call__
    await super().__call__(scope, receive, send)
  File "E:\cygwin64\git\crm_broker\venv\lib\site-packages\starlette\applications.py", line 118, in __call__
    await self.middleware_stack(scope, receive, send)
  File "E:\cygwin64\git\crm_broker\venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "E:\cygwin64\git\crm_broker\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "E:\cygwin64\git\crm_broker\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "E:\cygwin64\git\crm_broker\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "E:\cygwin64\git\crm_broker\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "E:\cygwin64\git\crm_broker\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "E:\cygwin64\git\crm_broker\venv\lib\site-packages\starlette\routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "E:\cygwin64\git\crm_broker\venv\lib\site-packages\starlette\routing.py", line 443, in handle
    await self.app(scope, receive, send)
  File "E:\cygwin64\git\crm_broker\venv\lib\site-packages\starlette\applications.py", line 118, in __call__
    await self.middleware_stack(scope, receive, send)
  File "E:\cygwin64\git\crm_broker\venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "E:\cygwin64\git\crm_broker\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "E:\cygwin64\git\crm_broker\venv\lib\site-packages\starlette\middleware\base.py", line 108, in __call__
    response = await self.dispatch_func(request, call_next)
  File "E:\cygwin64\git\crm_broker\.\starlette_admin\contrib\sqla\middleware.py", line 29, in dispatch
    response = await call_next(request)
  File "E:\cygwin64\git\crm_broker\venv\lib\site-packages\starlette\middleware\base.py", line 84, in call_next
    raise app_exc
  File "E:\cygwin64\git\crm_broker\venv\lib\site-packages\starlette\middleware\base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "E:\cygwin64\git\crm_broker\venv\lib\site-packages\starlette\middleware\sessions.py", line 86, in __call__
    await self.app(scope, receive, send_wrapper)
  File "E:\cygwin64\git\crm_broker\venv\lib\site-packages\starlette\middleware\base.py", line 108, in __call__
    response = await self.dispatch_func(request, call_next)
  File "E:\cygwin64\git\crm_broker\.\starlette_admin\auth.py", line 167, in dispatch
    return await call_next(request)
  File "E:\cygwin64\git\crm_broker\venv\lib\site-packages\starlette\middleware\base.py", line 84, in call_next
    raise app_exc
  File "E:\cygwin64\git\crm_broker\venv\lib\site-packages\starlette\middleware\base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "E:\cygwin64\git\crm_broker\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "E:\cygwin64\git\crm_broker\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "E:\cygwin64\git\crm_broker\venv\lib\site-packages\starlette\routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "E:\cygwin64\git\crm_broker\venv\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "E:\cygwin64\git\crm_broker\venv\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "E:\cygwin64\git\crm_broker\.\starlette_admin\base.py", line 316, in _render_api
    return JSONResponse(
  File "E:\cygwin64\git\crm_broker\venv\lib\site-packages\starlette\responses.py", line 196, in __init__
    super().__init__(content, status_code, headers, media_type, background)
  File "E:\cygwin64\git\crm_broker\venv\lib\site-packages\starlette\responses.py", line 55, in __init__
    self.body = self.render(content)
  File "E:\cygwin64\git\crm_broker\venv\lib\site-packages\starlette\responses.py", line 199, in render
    return json.dumps(
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Note is not JSON serializable
```

When set NotesField to text field it works everywhere:
```
    fields = [
        Post.id,
        NotesField("content")
    ]
```

**Comment by jowilf** [comment]
> The main idea to display some information in relation field. Currently, RelationField dispays only id.

You can customize it by overriding  [ModelView.repr](https://jowilf.github.io/starlette-admin/api/views/#starlette_admin.views.BaseModelView.repr). You can also override [ModelView.select2_result](https://jowilf.github.io/starlette-admin/api/views/#starlette_admin.views.BaseModelView.select2_result), [ModelView.select2_selection](https://jowilf.github.io/starlette-admin/api/views/#starlette_admin.views.BaseModelView.select2_selection) to customize the select2 rendering in forms.

For more customization, I recommend you to create your own field


> It displays information on detail. But when I'm trying to go to list ("admin/post/list") it displays base interface, but dont displays list of posts and return error in uvicorn

You need to provide a json serializable value for list action. By default StringField will cast your value into to str ([ref](https://github.com/jowilf/starlette-admin/blob/main/starlette_admin/fields.py#L221)). That is why you have this `[Note(content='rrrrrrrr', id=1, created_at=datetime.datetime(2023, 3, 15, 17, 21, 45, 410730), post_id=1))]`. You just need  to return string value for list.
Something like this
```py
class NoteField(TextAreaField):

    async def serialize_value(
            self, request: Request, value: Any, action: RequestAction
    ) -> str:
        if action == RequestAction.LIST:
            return ",".join([n.content for n in value])
        return value
```
More info -> https://jowilf.github.io/starlette-admin/advanced/custom-field/, https://jowilf.github.io/starlette-admin/api/fields/#starlette_admin.fields.BaseField

**Comment by jowilf** [comment]
Please @Ilya-Green , close the issue if it solved. Thank you

**Comment by Ilya-Green** [comment]
For some reason i cant recreate a problem. It works without errors. I don't know if it discussion will fully solution for someone but for me it work for now, so thank you very much.
