### ISSUE TITLE
Bug: Jinja2Templates.__init__() got an unexpected keyword argument 'extensions'

### ISSUE THREAD

**Issue by xmansyx** [jowilf/starlette-admin#271]
**Describe the bug**
i am trying to initialize the admin panel so i copied the Initialization code from documentation  and used my database url:
```
from sqlalchemy import create_engine
from starlette_admin.contrib.sqla import Admin

engine = create_engine("sqlite:///test.db", connect_args={"check_same_thread": False})

admin = Admin(engine)

```

then when i try to run the app i get this error:

````Traceback (most recent call last):
  File "/home/mansy/.cache/pypoetry/virtualenvs/myApp-6DfVpkI7-py3.10/bin/gunicorn", line 8, in <module>
    sys.exit(run())
  File "/home/mansy/.cache/pypoetry/virtualenvs/myApp-6DfVpkI7-py3.10/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/home/mansy/.cache/pypoetry/virtualenvs/myApp-6DfVpkI7-py3.10/lib/python3.10/site-packages/gunicorn/app/base.py", line 231, in run
    super().run()
  File "/home/mansy/.cache/pypoetry/virtualenvs/myApp-6DfVpkI7-py3.10/lib/python3.10/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/home/mansy/.cache/pypoetry/virtualenvs/myApp-6DfVpkI7-py3.10/lib/python3.10/site-packages/gunicorn/arbiter.py", line 58, in __init__
    self.setup(app)
  File "/home/mansy/.cache/pypoetry/virtualenvs/myApp-6DfVpkI7-py3.10/lib/python3.10/site-packages/gunicorn/arbiter.py", line 118, in setup
    self.app.wsgi()
  File "/home/mansy/.cache/pypoetry/virtualenvs/myApp-6DfVpkI7-py3.10/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/mansy/.cache/pypoetry/virtualenvs/myApp-6DfVpkI7-py3.10/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/mansy/.cache/pypoetry/virtualenvs/myApp-6DfVpkI7-py3.10/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/mansy/.cache/pypoetry/virtualenvs/myApp-6DfVpkI7-py3.10/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mansy/projects/Museml/apps/main.py", line 67, in <module>
    admin = Admin(engine)
  File "/home/mansy/.cache/pypoetry/virtualenvs/myApp-6DfVpkI7-py3.10/lib/python3.10/site-packages/starlette_admin/contrib/sqla/admin.py", line 41, in __init__
    super().__init__(
  File "/home/mansy/.cache/pypoetry/virtualenvs/myApp-6DfVpkI7-py3.10/lib/python3.10/site-packages/starlette_admin/base.py", line 90, in __init__
    self._setup_templates()
  File "/home/mansy/.cache/pypoetry/virtualenvs/myApp-6DfVpkI7-py3.10/lib/python3.10/site-packages/starlette_admin/base.py", line 211, in _setup_templates
    templates = Jinja2Templates(self.templates_dir, extensions=["jinja2.ext.i18n"])
TypeError: Jinja2Templates.__init__() got an unexpected keyword argument 'extensions'




**To Reproduce**
use initialization instruction on the documents

**Environment (please complete the following information):**
 - Starlette-Admin version 0.6.0
 - ORM/ODMs: SQLAlchemy

**Additional context**
Add any other context about the problem here.

**Comment by jowilf** [comment]
I'm unable to reproduce your issue, It may be linked to the Starlette/FastAPi version you're using. Can you try with the latest version of starlette ? Also, i recommend updating starlette-admin to the latest version.

**Comment by xmansyx** [comment]
@jowilf i am using FastApi version 0.71.0 Because it's a legacy project and upgrading it would cause some other problems in the mean time, that's why i am using older version of starlette-admin.

i tried to upgrade it to latest version of  starlette-admin (0.11.1) and still have the same error

**Comment by jowilf** [comment]
You can try with starlette-admin v0.5.5 but this is not recommended

**Comment by xmansyx** [comment]
that's working fine, thank you
