### ISSUE TITLE
Bug: ImageField not working 

### ISSUE THREAD

**Issue by IsmaelP19** [jowilf/starlette-admin#422]
**Describe the bug**
KeyError: 'path' thrown when uploaded image to an object.

**To Reproduce**
I am working on a project with FastAPI. To create the administrator panel, I am using Starlette Admin and everything worked just fine. However, I needed to upload a single image to each instance of a class called Facility. That's why I followed this [tutorial](https://jowilf.github.io/sqlalchemy-file/tutorial/quick-start/) and the rest of the documentation to make it happen. The upload goes well but when I try to edit the instance or view its details a 500 error is thrown. Here it is the full error trace:

```
Traceback (most recent call last):
  File "/home/ismael/.cache/pypoetry/virtualenvs/project-backend-qebpIpl6-py3.10/lib/python3.10/site-packages/anyio/streams/memory.py", line 98, in receive
    return self.receive_nowait()
  File "/home/ismael/.cache/pypoetry/virtualenvs/project-backend-qebpIpl6-py3.10/lib/python3.10/site-packages/anyio/streams/memory.py", line 93, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ismael/.cache/pypoetry/virtualenvs/project-backend-qebpIpl6-py3.10/lib/python3.10/site-packages/starlette/middleware/base.py", line 78, in call_next
    message = await recv_stream.receive()
  File "/home/ismael/.cache/pypoetry/virtualenvs/project-backend-qebpIpl6-py3.10/lib/python3.10/site-packages/anyio/streams/memory.py", line 118, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ismael/.cache/pypoetry/virtualenvs/project-backend-qebpIpl6-py3.10/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/ismael/.cache/pypoetry/virtualenvs/project-backend-qebpIpl6-py3.10/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/ismael/.cache/pypoetry/virtualenvs/project-backend-qebpIpl6-py3.10/lib/python3.10/site-packages/fastapi/applications.py", line 292, in __call__
    await super().__call__(scope, receive, send)
  File "/home/ismael/.cache/pypoetry/virtualenvs/project-backend-qebpIpl6-py3.10/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/ismael/.cache/pypoetry/virtualenvs/project-backend-qebpIpl6-py3.10/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/ismael/.cache/pypoetry/virtualenvs/project-backend-qebpIpl6-py3.10/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/ismael/.cache/pypoetry/virtualenvs/project-backend-qebpIpl6-py3.10/lib/python3.10/site-packages/starlette/middleware/sessions.py", line 86, in __call__
    await self.app(scope, receive, send_wrapper)
  File "/home/ismael/.cache/pypoetry/virtualenvs/project-backend-qebpIpl6-py3.10/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/home/ismael/.cache/pypoetry/virtualenvs/project-backend-qebpIpl6-py3.10/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/ismael/.cache/pypoetry/virtualenvs/project-backend-qebpIpl6-py3.10/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/ismael/.cache/pypoetry/virtualenvs/project-backend-qebpIpl6-py3.10/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/home/ismael/.cache/pypoetry/virtualenvs/project-backend-qebpIpl6-py3.10/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/home/ismael/.cache/pypoetry/virtualenvs/project-backend-qebpIpl6-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/ismael/.cache/pypoetry/virtualenvs/project-backend-qebpIpl6-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 443, in handle
    await self.app(scope, receive, send)
  File "/home/ismael/.cache/pypoetry/virtualenvs/project-backend-qebpIpl6-py3.10/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/ismael/.cache/pypoetry/virtualenvs/project-backend-qebpIpl6-py3.10/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/ismael/.cache/pypoetry/virtualenvs/project-backend-qebpIpl6-py3.10/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/ismael/.cache/pypoetry/virtualenvs/project-backend-qebpIpl6-py3.10/lib/python3.10/site-packages/starlette/middleware/base.py", line 108, in __call__
    response = await self.dispatch_func(request, call_next)
  File "/home/ismael/.cache/pypoetry/virtualenvs/project-backend-qebpIpl6-py3.10/lib/python3.10/site-packages/starlette_admin/contrib/sqla/middleware.py", line 28, in dispatch
    return await call_next(request)
  File "/home/ismael/.cache/pypoetry/virtualenvs/project-backend-qebpIpl6-py3.10/lib/python3.10/site-packages/starlette/middleware/base.py", line 84, in call_next
    raise app_exc
  File "/home/ismael/.cache/pypoetry/virtualenvs/project-backend-qebpIpl6-py3.10/lib/python3.10/site-packages/starlette/middleware/base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/home/ismael/.cache/pypoetry/virtualenvs/project-backend-qebpIpl6-py3.10/lib/python3.10/site-packages/starlette/middleware/base.py", line 108, in __call__
    response = await self.dispatch_func(request, call_next)
  File "/home/ismael/.cache/pypoetry/virtualenvs/project-backend-qebpIpl6-py3.10/lib/python3.10/site-packages/starlette_admin/auth.py", line 286, in dispatch
    return await call_next(request)
  File "/home/ismael/.cache/pypoetry/virtualenvs/project-backend-qebpIpl6-py3.10/lib/python3.10/site-packages/starlette/middleware/base.py", line 84, in call_next
    raise app_exc
  File "/home/ismael/.cache/pypoetry/virtualenvs/project-backend-qebpIpl6-py3.10/lib/python3.10/site-packages/starlette/middleware/base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/home/ismael/.cache/pypoetry/virtualenvs/project-backend-qebpIpl6-py3.10/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/ismael/.cache/pypoetry/virtualenvs/project-backend-qebpIpl6-py3.10/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/ismael/.cache/pypoetry/virtualenvs/project-backend-qebpIpl6-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/ismael/.cache/pypoetry/virtualenvs/project-backend-qebpIpl6-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/ismael/.cache/pypoetry/virtualenvs/project-backend-qebpIpl6-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/ismael/.cache/pypoetry/virtualenvs/project-backend-qebpIpl6-py3.10/lib/python3.10/site-packages/starlette_admin/base.py", line 414, in _render_edit
    "obj": await model.serialize(obj, request, RequestAction.EDIT),
  File "/home/ismael/.cache/pypoetry/virtualenvs/project-backend-qebpIpl6-py3.10/lib/python3.10/site-packages/starlette_admin/views.py", line 538, in serialize
    obj_serialized[field.name] = await self.serialize_field_value(
  File "/home/ismael/.cache/pypoetry/virtualenvs/project-backend-qebpIpl6-py3.10/lib/python3.10/site-packages/starlette_admin/views.py", line 497, in serialize_field_value
    return await field.serialize_value(request, value, action)
  File "/home/ismael/.cache/pypoetry/virtualenvs/project-backend-qebpIpl6-py3.10/lib/python3.10/site-packages/starlette_admin/contrib/sqla/fields.py", line 38, in serialize_value
    return _serialize_sqlalchemy_file_library(
  File "/home/ismael/.cache/pypoetry/virtualenvs/project-backend-qebpIpl6-py3.10/lib/python3.10/site-packages/starlette_admin/contrib/sqla/fields.py", line 59, in _serialize_sqlalchemy_file_library
    path = item["path"]
  File "/home/ismael/.cache/pypoetry/virtualenvs/project-backend-qebpIpl6-py3.10/lib/python3.10/site-packages/sqlalchemy_file/base.py", line 15, in __getitem__
    return dict.__getitem__(self, key)
KeyError: 'path'
```

**Environment (please complete the following information):**
 - Starlette-Admin version: 0.11.2
 - [SQLAlchemy-File](https://jowilf.github.io/sqlalchemy-file) version: 0.6.0
 - FastAPI version: 0.103.2
 - ORM/ODMs: SQLAlchemy (v2.0.21)

I have more packages but I thinkg these are the most important. However, if you need more information please let me know.

**Additional context**
This issue is not exactly of Starlette-Admin, but since @jowilf is also the creator of SQLAlchemy-File I was hoping you could help me.

I would really appreciate your help with this problem.

**Comment by jowilf** [comment]
Can you provide a minimal example that reproduces the bug? This issue can only occur if you modify (outside sqlalchemy) the column containing the file information in the database.

**Comment by IsmaelP19** [comment]
Thanks for your response. I will create a minimal example where you can reproduce the bug. 
As to this issue, I do not modify outside sqlalchemy the column value. What I do is create an instance and if I go to the database manager (for example, adminer) you can see the content of the column with all the attributes the ImageField has loaded into it. However, if I go to details page of this instance on the starlette-admin page, the above error occurs (also when I try to edit them).

I will let you know as soon as I have the repo working.

**Comment by IsmaelP19** [comment]
When creating the [minimal example](https://github.com/IsmaelP19/imagefield-bug), I discovered the bug is not present, so there must be differences to my actual project that is making this bug. I found that on my project, the Alembic migration does not change the image attribute from string to json as it does on this repo.

However, as I say on the README, there I have another issue that is related to the edit and view options. I think it must be related with the primary keys or something, because it tries to go to an undefined route. Besides, the relationship between User and Facility here is not working as expected, because you can't add any user to any relationship as it is specified on the code.
Shall I create another bug or change this one?

I would really appreciate your help through this issue. I will continue looking why on my other project the imagefield is throwing this error.
